name: Precommit

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Caching
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "harper"
      - uses: extractions/setup-just@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - name: Install `wasm-pack`
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Precommit
        run: just precommit
